name: Automatic Security Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 1,15 * *" # At 08:00 on day-of-month 1 and 15

jobs:
  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    container:
      image: node:20.19
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn install
      - name: Run yarn audit
        id: audit
        run: yarn audit --no-color --json > yarn-report.json
        continue-on-error: true # we still want to upload the report
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: yarn-audit-report-boomerang-opentelemetry-plugin
          path: yarn-report.json
      # Since GitHub cannot send emails directly, we use an external API
      - name: Send Notification via Resend
        run: |
          curl -X POST https://api.resend.com/emails \
            -H "Authorization: Bearer ${{ secrets.RESEND_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{
              "from": "inspectIT Ocelot DepCheck <inspectit-ocelot-depcheck@resend.dev>",
              "to": ["info.inspectit@novatec-gmbh.de"],
              "subject": "Boomerang-OTel-PluginDependency-Check Report - ${{ steps.depcheck.outcome }}",
              "html": "<p>The Dependency-Check for ${{ github.repository }} completed with status: <strong>${{ steps.depcheck.outcome }}</strong></p><p>Please check the report here: <a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>View Report</a></p>"
            }'
      # if yarn audit failed, the job should also fail, but only after the results were uploaded
      - name: Validate yarn audit outcome
        if: ${{ steps.audit.outcome == 'failure' }}
        run: |
          echo "Yarn audit failed"
          exit 1
